In [1]:
import pandas as pd
import numpy as np
import os
import sys
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

In [2]:
ratings_200 = pd.read_csv("/home/grigriko/general_model/movies_for_all9599_mtx_master.csv")
ratings_200

414  599  474  448  274  610   68  380  606  288  ...   27  184  376  \
0     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  0.0  1.0   
1     1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0   
2     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0   
3     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0   
4     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  1.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9505  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9506  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9507  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9508  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9509  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      377  524   52  268  369  314  movie_id  
0     0.0  0.0  1.0  1.0  0.0  1.0       356  
1     0.0  1.0  1.0  0.0  0.0  1.0       318  
2     0.0  0.0  0.0  0.0  0.0  1.0       296  
3     0.0  1.0  0.0  0.0  0.0  1.0       593  
4     0.0  0.0  1.0  1.0  1.0  0.0      2571  
...   ...  ...  ...  ...  ...  ...       ...  
9505  0.0  0.0  0.0  0.0  0.0  0.0     80478  
9506  0.0  0.0  0.0  0.0  0.0  0.0     80553  
9507  0.0  0.0  0.0  0.0  0.0  0.0     81191  
9508  0.0  0.0  0.0  0.0  0.0  0.0     83976  
9509  0.0  0.0  0.0  0.0  0.0  0.0    163981  

[9510 rows x 201 columns]

In [3]:
top_reviewers_df = pd.read_csv("/home/grigriko/general_model/general_modeluser_top_reviewers.csv")
top_reviewers_df.head()
subj_idx = top_reviewers_df['userId'][:200].astype(str)
# subj_idx.index = subj_idx
# subj_idx = subj_idx.drop(['434', '570', '331', '230', '141', '475'])
subj_idx

0      414
1      599
2      474
3      448
4      274
      ... 
195    524
196     52
197    268
198    369
199    314
Name: userId, Length: 200, dtype: object

In [6]:
top_user = pd.DataFrame(rating_df.groupby(['userId'])['userId'].count())
top_user.columns = ['count']
top_user = top_user.sort_values(by='count', ascending=False)
user_list = top_user.index
user_list

Int64Index([414, 599, 474, 448, 274, 610,  68, 380, 606, 288,
            ...
            147, 257, 406, 431, 278, 442, 569, 320, 576,  53],
           dtype='int64', name='userId', length=610)

In [66]:
rating_df = pd.read_csv("//home//grigriko//anaconda3//envs//py39//dataset//ratings.csv")
rating_df = rating_df.drop('timestamp', axis = 1)
# rating_df['rating'] = rating_df['rating'].replace([0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0], 1.0)
rating_df

userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [67]:
top_user_0 = pd.DataFrame(rating_df.groupby(['movieId'])['movieId'].count())
top_user_0.columns = ['count']
top_user_0

count
movieId       
1          215
2          110
3           52
4            7
5           49
...        ...
193581       1
193583       1
193585       1
193587       1
193609       1

[9724 rows x 1 columns]

In [69]:
top_movie = top_user_0.sort_values(by='count', ascending=False)
top_movie.to_csv("/home/grigriko/knn_cf/item_based/nonorm/top_movies.csv")

In [27]:
test_a = ratings_200.iloc[4114, :149]
test_b = ratings_200.iloc[7073, :149]
print(test_a, test_b)
test_corr = test_a.corr(test_b)
print(test_corr)

414    0.0
599    1.0
474    0.0
448    0.0
274    0.0
      ... 
479    0.0
266    0.0
153    0.0
74     0.0
279    0.0
Name: 4114, Length: 149, dtype: float64 414    0.0
599    1.0
474    0.0
448    0.0
274    0.0
      ... 
479    0.0
266    0.0
153    0.0
74     0.0
279    0.0
Name: 7073, Length: 149, dtype: float64
1.0


In [20]:
def find_best_corr(rating_a, rating_b):
#     print(rating_a, rating_b)
    corr_ab = np.corrcoef(rating_a, rating_b)
#     print(corr_ab)
    arranged_corr = 1 - corr_ab
#     print(arranged_corr)
#     print(arranged_corr[0, 1])
    return arranged_corr[0, 1]

In [59]:
def create_model(rating_matrix, k=20):
    """
    :param R : numpy array of item representations
    :param k : number of nearest neighbors to return    
    :return model : our knn model
    """    
    model = NearestNeighbors(metric='correlation', n_neighbors=k+1, algorithm='brute')
    model.fit(rating_matrix)    
    return model

In [60]:
def nearest_neighbors(rating_matrix, model):
    """
    compute the top n similar items for each item.    
    :param rating_matrix : items representations
    :param model : nearest neighbors model    
    :return similarities, neighbors
    """    
    similarities, neighbors = model.kneighbors(rating_matrix)    
#     display(similarities)
#     display(neighbors)
    return similarities, neighbors

In [45]:
model = create_model(ratings_200.iloc[:, :150], k=100)

similarities, neighbors = nearest_neighbors(ratings_200.iloc[:, :150], model)

/home/grigriko/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/lib/function_base.py:2829: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/grigriko/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/lib/function_base.py:2830: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


In [46]:
print(similarities)
print(neighbors)

[[0.         0.63843837 0.69141652 ... 0.81662406 0.81889511 0.81889511]
 [0.         0.6031746  0.65730232 ... 0.77709448 0.77709448 0.77732003]
 [0.         0.47120705 0.48889541 ... 0.77616076 0.77616076 0.77616076]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[[   0   10   48 ...  370  187  199]
 [   1    3  113 ...  273  204  310]
 [   2   28   76 ...  651  497  226]
 ...
 [9471 9459 9458 ... 9399 9407 9507]
 [9471 9459 9458 ... 9399 9407 9507]
 [6759 6711 6708 ... 6782 6770 6737]]


In [47]:
df_similarities = pd.DataFrame(similarities)
display(df_similarities)
df_neighbors = pd.DataFrame(neighbors)
display(df_neighbors)

0         1         2         3         4         5    \
0     0.000000e+00  0.638438  0.691417  0.703932  0.707361  0.709516   
1     0.000000e+00  0.603175  0.657302  0.661010  0.668043  0.669421   
2     0.000000e+00  0.471207  0.488895  0.533699  0.564126  0.570051   
3     0.000000e+00  0.570051  0.603175  0.629672  0.638924  0.645001   
4     1.110223e-16  0.501473  0.590054  0.591937  0.595228  0.596890   
...            ...       ...       ...       ...       ...       ...   
9505  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000   
9506  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000   
9507  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000   
9508  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000   
9509  0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000   

           6         7         8         9    ...       91        92   \
0     0.710597  0.714876  0.719776  0.721607  ...  0.815015  0.815015   
1     0.672822  0.673238  0.683344  0.691338  ...  0.773652  0.773652   
2     0.575253  0.615827  0.619696  0.621051  ...  0.771287  0.774257   
3     0.652828  0.663471  0.670750  0.673347  ...  0.776587  0.777094   
4     0.612512  0.627322  0.634852  0.641943  ...  0.764789  0.764789   
...        ...       ...       ...       ...  ...       ...       ...   
9505  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000   
9506  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000   
9507  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000   
9508  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000   
9509  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000   

           93        94        95        96        97        98        99   \
0     0.815309  0.815309  0.816231  0.816231  0.816550  0.816624  0.818895   
1     0.773652  0.773786  0.773786  0.776426  0.777094  0.777094  0.777094   
2     0.774779  0.774779  0.774779  0.775457  0.776161  0.776161  0.776161   
3     0.777094  0.777320  0.777320  0.777791  0.778695  0.778938  0.781782   
4     0.765859  0.766701  0.767111  0.767111  0.769911  0.769911  0.769911   
...        ...       ...       ...       ...       ...       ...       ...   
9505  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9506  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9507  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9508  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9509  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

           100  
0     0.818895  
1     0.777320  
2     0.776161  
3     0.781782  
4     0.769911  
...        ...  
9505  0.000000  
9506  0.000000  
9507  0.000000  
9508  0.000000  
9509  0.000000  

[9510 rows x 101 columns]

0     1     2     3     4     5     6     7     8     9    ...   91   \
0        0    10    48    26    14    53   155    58    15    68  ...   270   
1        1     3   113     9    76    10    78     2    14    92  ...   494   
2        2    28    76    10    14     3    69    31   127    13  ...   880   
3        3     2     1    13    76   108    28    45   110   194  ...     5   
4        4    10    35    20    24   112    70    56    47   139  ...   320   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
9505  9471  9459  9458  9457  9456  9455  5507  9454  9453  9451  ...  9404   
9506  9471  9459  9458  9457  9456  9455  5507  9454  9453  9451  ...  9404   
9507  9471  9459  9458  9457  9456  9455  5507  9454  9453  9451  ...  9404   
9508  9471  9459  9458  9457  9456  9455  5507  9454  9453  9451  ...  9404   
9509  6759  6711  6708  6706  6702  6677  6701  6700  6678  6697  ...  6633   

       92    93    94    95    96    97    98    99    100  
0      279   147   167   916   573    32   370   187   199  
1      491   362  1373  1249   232   658   273   204   310  
2      172    47   194   171   165   739   651   497   226  
3      522   669   222   347   928   114   219   615   931  
4      346   453   156   466   532    51   333   270   334  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
9505  9403  9402  9401  9303  9316  9317  9399  9407  9507  
9506  9403  9402  9401  9303  9316  9317  9399  9407  9507  
9507  9403  9402  9401  9303  9316  9317  9399  9407  9507  
9508  9403  9402  9401  9303  9316  9317  9399  9407  9507  
9509  6619  6612  6772  6774  6777  6780  6782  6770  6737  

[9510 rows x 101 columns]

In [48]:
one_minus_itself = lambda x: 1 - x
df_similarities = df_similarities.applymap(one_minus_itself)
df_similarities

0         1         2         3         4         5         6    \
0     1.0  0.361562  0.308583  0.296068  0.292639  0.290484  0.289403   
1     1.0  0.396825  0.342698  0.338990  0.331957  0.330579  0.327178   
2     1.0  0.528793  0.511105  0.466301  0.435874  0.429949  0.424747   
3     1.0  0.429949  0.396825  0.370328  0.361076  0.354999  0.347172   
4     1.0  0.498527  0.409946  0.408063  0.404772  0.403110  0.387488   
...   ...       ...       ...       ...       ...       ...       ...   
9505  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
9506  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
9507  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
9508  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
9509  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

           7         8         9    ...       91        92        93   \
0     0.285124  0.280224  0.278393  ...  0.184985  0.184985  0.184691   
1     0.326762  0.316656  0.308662  ...  0.226348  0.226348  0.226348   
2     0.384173  0.380304  0.378949  ...  0.228713  0.225743  0.225221   
3     0.336529  0.329250  0.326653  ...  0.223413  0.222906  0.222906   
4     0.372678  0.365148  0.358057  ...  0.235211  0.235211  0.234141   
...        ...       ...       ...  ...       ...       ...       ...   
9505  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
9506  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
9507  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
9508  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
9509  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   

           94        95        96        97        98        99        100  
0     0.184691  0.183769  0.183769  0.183450  0.183376  0.181105  0.181105  
1     0.226214  0.226214  0.223574  0.222906  0.222906  0.222906  0.222680  
2     0.225221  0.225221  0.224543  0.223839  0.223839  0.223839  0.223839  
3     0.222680  0.222680  0.222209  0.221305  0.221062  0.218218  0.218218  
4     0.233299  0.232889  0.232889  0.230089  0.230089  0.230089  0.230089  
...        ...       ...       ...       ...       ...       ...       ...  
9505  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
9506  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
9507  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
9508  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
9509  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  

[9510 rows x 101 columns]

In [ ]:
#類似度の対象に自分が入っている映画を類似度から除去
for idx in df_neighbors.index:
    for col in df_neighbors.columns:
        if df_neighbors.loc[idx, col] == idx:
            print(df_similarities.loc[idx, col])
            df_similarities.loc[idx, col] = 0

In [50]:
df_similarities = df_similarities.fillna(0)
df_similarities.to_csv("/home/grigriko/knn_cf/item_based/nonorm/arranged_similarities_1-pearson_100.csv")

In [57]:
def predict(userid, itemid, df_similarities, df_neighbors):
    """
    Make rating prediction for user userid on item itemid    
    :param userid : id of the active user
    :param itemid : id of the item for which we are making prediction        
    :return r_hat : predicted rating
    """
    dim = len(df_similarities.columns)
    # Get items similar to item itemid with their corresponding similarities
    item_neighbors = df_neighbors.loc[itemid, :]
    item_similarities = df_similarities.loc[itemid, :]
    
    # get ratings of user with id userid
    uratings = ratings_200[userid]
    
    # similar items rated by item the user of i
    scores = ratings_200.loc[item_neighbors, userid].to_numpy().reshape(1, dim)
    
    sims = item_similarities.to_numpy().reshape(dim, 1)
    
    dot = np.dot(scores, sims)
    som = np.sum(np.abs(sims))

    if som == 0:
        return np.nan
    elif dot == 0:
        return 0
    
    return dot / som

In [51]:
#1-simを類似度にしているほう
df_pred = pd.DataFrame()
for userid in subj_idx[151:]:
    pred_list = []
    for itemid in range(9510):
        pred = predict(userid, itemid)
        if pred == 0 or np.isnan(pred):
            pass
        else:
            pred = pred[0, 0]
        pred_list.append(pred)
    df_pred[userid] = pred_list

In [52]:
df_pred.to_csv("/home/grigriko/knn_cf/item_based/nonorm/score_1-pearson_sim100_nonan.csv")

In [56]:
def leave_one_score(num, user_id, saved_dir, k_neighbor):
    subj_idx = top_reviewers_df['userId'][:200].astype(str)
    subj_leave_one = subj_idx.drop(num)#numは0から199までの数字
    
    model = create_model(rating_matrix=ratings_200.loc[:, subj_leave_one], k=k_neighbor)

    similarities, neighbors = nearest_neighbors(ratings_200.loc[:, subj_leave_one], model) 
    
    df_similarities = pd.DataFrame(similarities)

    df_neighbors = pd.DataFrame(neighbors)

    one_minus_itself = lambda x: 1 - x
    df_similarities = df_similarities.applymap(one_minus_itself)
    
    for idx in df_neighbors.index:
        for col in df_neighbors.columns:
            if df_neighbors.loc[idx, col] == idx:
                df_similarities.loc[idx, col] = 0
                
    df_similarities = df_similarities.fillna(0)
    
#     df_similarities.to_csv(saved_dir + "/similarities/leave_one_100_" + user_id + ".csv")
#     df_neighbors.to_csv(saved_dir + "/neighbors/leave_one_100_" + user_id + ".csv")

#     df_similarities = pd.read_csv(saved_dir + "/similarities/leave_one_100_" + user_id + ".csv")
#     df_neighbors = pd.read_csv(saved_dir + "/neighbors/leave_one_100_" + user_id + ".csv")
    
    
    pred_list = []
    for itemid in range(9510):
        pred = predict(user_id, itemid, df_similarities, df_neighbors)
        if pred == 0 or np.isnan(pred):
            pass
        else:
            pred = pred[0, 0]
        pred_list.append(pred)
    return pred_list

In [ ]:
#leave one out実行
df_pred = pd.DataFrame()
num = 0
save_dir = "/home/grigriko/knn_cf/item_based/nonorm"
k_neighbor = 100
for user_id in subj_idx:
    pred_list = leave_one_score(num, user_id, save_dir, k_neighbor)
#     print(pred_list)
    df_pred[user_id] = pred_list
#     display(df_pred)
    num += 1
    print(num)
display(df_pred)
df_pred.to_csv("/home/grigriko/knn_cf/item_based/nonorm/score_1-pearson_sim100_0622.csv")

In [96]:
df_pred_nonan = df_pred.fillna(0)
df_pred_nonan.to_csv("/home/grigriko/knn_cf/item_based/nonorm/scorenonan_1-pearson_sim500_leave_one_out.csv")

In [31]:
df_pred = pd.read_csv("/home/grigriko/knn_cf/item_based/nonorm/score_1-pearson_sim500_leave_one_out.csv")
df_pred = df_pred.drop('Unnamed: 0', axis=1)
df_pred

414       599       474       448       274       610        68  \
0     0.896072  0.755693  0.633569  0.619057  0.649214  0.478699  0.763312   
1     0.867394  0.682173  0.553839  0.543821  0.640263  0.581404  0.630428   
2     0.837441  0.767189  0.664154  0.524764  0.581999  0.451778  0.597005   
3     0.787349  0.720603  0.669208  0.436680  0.496299  0.351113  0.500201   
4     0.907609  0.825798  0.572782  0.682577  0.771280  0.597898  0.811043   
...        ...       ...       ...       ...       ...       ...       ...   
9505  0.151415  0.130842  0.087697  0.119845  0.062162  0.133801  0.064556   
9506  0.151415  0.130842  0.087697  0.119845  0.062162  0.133801  0.064556   
9507  0.151415  0.130842  0.087697  0.119845  0.062162  0.133801  0.064556   
9508  0.151415  0.130842  0.087697  0.119845  0.062162  0.133801  0.064556   
9509  0.076472  0.168506  0.018595  0.083235  0.120419       NaN  0.017127   

           380       606       288  ...        15        27       184  \
0     0.532318  0.461733  0.498960  ...  0.137642  0.093051  0.035782   
1     0.480129  0.376397  0.408406  ...  0.143057  0.041611  0.034645   
2     0.453747  0.496149  0.483619  ...  0.108114  0.061932  0.023207   
3     0.400872  0.433188  0.478484  ...  0.096562  0.092416  0.008913   
4     0.683085  0.460022  0.524620  ...  0.187519  0.086522  0.033913   
...        ...       ...       ...  ...       ...       ...       ...   
9505  0.063433  0.072863  0.023162  ...  0.004141  0.000000  0.018179   
9506  0.063433  0.072863  0.023162  ...  0.004141  0.000000  0.018179   
9507  0.063433  0.072863  0.023162  ...  0.004141  0.000000  0.018179   
9508  0.063433  0.072863  0.023162  ...  0.004141  0.000000  0.018179   
9509  0.110864  0.013295  0.012144  ...  0.002245  0.000000  0.001663   

           376       377       524        52       268       369       314  
0     0.180476  0.038830  0.140358  0.112029  0.090122  0.123964  0.124637  
1     0.145353  0.033209  0.085949  0.139383  0.055550  0.096374  0.081738  
2     0.135150  0.045668  0.136463  0.090643  0.119508  0.120130  0.106864  
3     0.122926  0.047953  0.139479  0.057354  0.089587  0.074633  0.111623  
4     0.188240  0.034806  0.089625  0.133375  0.100683  0.139277  0.061451  
...        ...       ...       ...       ...       ...       ...       ...  
9505  0.002378  0.004886  0.001811  0.006976  0.004147  0.005824  0.000000  
9506  0.002378  0.004886  0.001811  0.006976  0.004147  0.005824  0.000000  
9507  0.002378  0.004886  0.001811  0.006976  0.004147  0.005824  0.000000  
9508  0.002378  0.004886  0.001811  0.006976  0.004147  0.005824  0.000000  
9509  0.000000  0.001663  0.001167  0.005051  0.001282  0.000000  0.000000  

[9510 rows x 200 columns]

In [62]:
df_pred_sim100 = pd.read_csv("/home/grigriko/knn_cf/item_based/nonorm/score_1-pearson_sim100_0622.csv")
df_pred_sim100 = df_pred_sim100.drop('Unnamed: 0', axis=1)
df_pred_sim100

414       599       474       448       274       610        68  \
0     0.973167  0.860407  0.811100  0.727785  0.833132  0.579265  0.917275   
1     0.951629  0.823497  0.784226  0.720606  0.831321  0.717491  0.842052   
2     0.961250  0.897514  0.791185  0.639159  0.840511  0.629872  0.755001   
3     0.892456  0.863790  0.903051  0.592722  0.747241  0.576664  0.690624   
4     1.000000  0.965876  0.785765  0.835507  0.954151  0.777493  0.964347   
...        ...       ...       ...       ...       ...       ...       ...   
9505  0.010000  0.029703  0.009901  0.039604  0.000000  0.050000  0.010000   
9506  0.010000  0.030000  0.009901  0.039604  0.000000  0.050000  0.010000   
9507  0.010000  0.029703  0.009901  0.039604  0.000000  0.049505  0.010000   
9508  0.010000  0.029703  0.009901  0.039604  0.000000  0.049505  0.010000   
9509  0.009901  0.108911  0.000000  0.049505  0.089109       NaN  0.000000   

           380       606       288  ...        15        27       184  \
0     0.645239  0.681353  0.704835  ...  0.259143  0.175157  0.026990   
1     0.584173  0.588761  0.593568  ...  0.280012  0.038237  0.051284   
2     0.628758  0.713033  0.596194  ...  0.235160  0.068492  0.009731   
3     0.577050  0.666209  0.658530  ...  0.203141  0.150474  0.000000   
4     0.851012  0.743603  0.755808  ...  0.376246  0.148423  0.047090   
...        ...       ...       ...  ...       ...       ...       ...   
9505  0.000000  0.049505  0.010000  ...  0.000000  0.000000  0.000000   
9506  0.000000  0.049505  0.009901  ...  0.000000  0.000000  0.000000   
9507  0.000000  0.049505  0.009901  ...  0.000000  0.000000  0.000000   
9508  0.000000  0.049505  0.009901  ...  0.000000  0.000000  0.000000   
9509  0.079208  0.000000  0.000000  ...  0.000000  0.000000  0.000000   

           376       377       524        52       268       369       314  
0     0.305424  0.055359  0.230479  0.162632  0.170253  0.244883  0.215211  
1     0.317842  0.033026  0.098155  0.250172  0.095148  0.222199  0.147112  
2     0.249553  0.053059  0.264758  0.137831  0.254473  0.211228  0.210110  
3     0.249588  0.080847  0.285752  0.071836  0.116311  0.127613  0.229403  
4     0.419070  0.047514  0.152939  0.201197  0.163560  0.273302  0.069698  
...        ...       ...       ...       ...       ...       ...       ...  
9505  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9506  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9507  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9508  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9509  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  

[9510 rows x 200 columns]

In [64]:
def calculate_corr(df_score, ratings_200, idx):
    start_list = [2500, 2500, 3500, 4500, 5500, 6500]
    end_list = [9509, 3499, 4499, 5499, 6499, 9509]
    corr_list = []
    ratings_200 = ratings_200.drop('movie_id', axis=1)
    for i in range(len(start_list)):
        divided_output = df_score.loc[start_list[i]:end_list[i], :]
        true_output = ratings_200.loc[start_list[i]:end_list[i], :]
        
        nan_idx = divided_output.loc[np.isnan(divided_output[idx]), idx].index
#         print(nan_idx)
        output_nonan = divided_output.drop(nan_idx)
#         display(output_nonan)
        true_nonan = true_output.drop(nan_idx)
#         display(true_nonan)
        
        corr = output_nonan[idx].corr(true_nonan[idx])
        corr_list.append(corr)
        
    return corr_list

In [13]:
def make_df_corr(corr_list, df_corr, idx):
    df_corr.loc[idx, :] = corr_list
    return df_corr

In [65]:
corr_columns = ['2500-9509', '2500-3499', '3500-4499', '4500-5499', '5500-6499', '6500-9509']
df_corr = pd.DataFrame(index = subj_idx, columns = corr_columns)

for idx in subj_idx:
    corr_list = calculate_corr(df_pred_sim100, ratings_200, idx)
    df_corr = make_df_corr(corr_list, df_corr, idx)
display(df_corr)
# df_corr.to_csv("/home/grigriko/knn_cf/item_based/nonorm/corr_leave_one_out/sim100_compare_corr.csv")

2500-9509 2500-3499 3500-4499 4500-5499 5500-6499 6500-9509
userId                                                            
414     0.159501  0.093023  0.199747  0.186348  0.360884       NaN
599     0.118885  0.151185  0.098855   0.12385  0.194516       NaN
474     0.239592  0.278694  0.319555  0.257206   0.48211       NaN
448     0.208264  0.261026  0.250703   0.34571  0.382361       NaN
274     0.216771  0.363802  0.224345  0.225778  0.112127       NaN
...          ...       ...       ...       ...       ...       ...
524     0.030201   0.11718       NaN -0.006949       NaN       NaN
52      0.071554  0.185518  0.025286       NaN       NaN       NaN
268     0.090946  0.159208  0.162389  0.009101       NaN       NaN
369    -0.003604  0.006746 -0.024118       NaN       NaN       NaN
314     0.049512  0.012442       NaN  0.194475  0.094667       NaN

[200 rows x 6 columns]